#ifndef TCPCLIENTCOM_GLOBAL_H
#define TCPCLIENTCOM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPCLIENTCOM_LIBRARY)
#  define TCPCLIENTCOMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TCPCLIENTCOMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPCLIENTCOM_GLOBAL_H
